"""empty message

Revision ID: 2ff33425211f
Revises: 
Create Date: 2020-11-30 18:03:14.505628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff33425211f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', sa.String(length=30), nullable=False))
    op.drop_index('ix_user_password', table_name='user')
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.create_index('ix_user_password', 'user', ['password'], unique=1)
    op.drop_column('user', 'city')
    # ### end Alembic commands ###
